# Generated by Django 5.1.7 on 2025-03-16 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConstructionType', models.CharField(max_length=200)),
                ('ConstructionName', models.CharField(max_length=200)),
                ('CementQuality', models.CharField(max_length=200)),
                ('CementPrice', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(200)])),
                ('BrickQuality', models.CharField(max_length=200)),
                ('BrickPrice', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(20)])),
                ('SandQuality', models.CharField(max_length=200)),
                ('SandPrice', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(200)])),
                ('IronQuality', models.CharField(max_length=200)),
                ('IronPrice', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(20000)])),
                ('EnvironmentalCondition', models.CharField(max_length=100)),
                ('Seller', models.CharField(max_length=500)),
                ('Price', models.BigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5000000), django.core.validators.MinValueValidator(2000000)])),
            ],
        ),
    ]
