# Generated by Django 5.1.7 on 2025-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("con_app", "0002_environmentalcondition_seller_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="construction",
            name="EnvironmentalCondition",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="construction",
            name="Seller",
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name="EnvironmentalCondition",
        ),
        migrations.DeleteModel(
            name="Seller",
        ),
    ]
