# Generated by Django 5.1.7 on 2025-04-05 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("con_app", "0003_alter_construction_environmentalcondition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentalCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "contact_info",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="construction",
            name="EnvironmentalCondition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="con_app.environmentalcondition",
            ),
        ),
        migrations.AlterField(
            model_name="construction",
            name="Seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="con_app.seller",
            ),
        ),
    ]
