# Generated by Django 5.1.7 on 2025-04-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("con_app", "0004_environmentalcondition_seller_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentalcondition",
            name="precations",
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
