# Generated by Django 5.1.7 on 2025-04-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("con_app", "0006_alter_environmentalcondition_precations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentalcondition",
            name="precations",
            field=models.TextField(default=None, max_length=10000),
        ),
    ]
